# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"subplots": "00_core.ipynb",
         "show_image": "00_core.ipynb",
         "set_seed": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://austinyhc.github.io/sensorai/"

git_url = "https://github.com/austinyhc/sensorai/tree/master/"

def custom_doc_links(name): return None
