# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_utils.ipynb (unless otherwise specified).

__all__ = ['moving_average']

# Cell
from .imports import *
from .tf_imports import *

# Cell
def moving_average(x, window=5):
    """
    Return a moving-window average.
    :param x: a numpy array
    :param window: an integer, number of data points for window size.
    """
    return (pd.DataFrame(x)
                .rolling(window=window, min_periods=1)
                .mean()
                .values
                .squeeze())

# Cell
def _pca(x, k=2):
    x = x-tf.math.reduce_mean(x,axis=0)
    S,U,V = tf.linalg.svd(tf.transpose(x))
    return tf.matmul(x,U[:,:k])