baseurl: /sensorai/
collections:
  tooltips:
    output: false
company_name: Austin Chen
defaults:
- scope:
    path: ''
    type: pages
  values:
    comments: true
    layout: page
    search: true
    sidebar: home_sidebar
    topnav: topnav
- scope:
    path: ''
    type: tooltips
  values:
    comments: true
    layout: page
    search: true
    tooltip: true
description: A Python library that makes deep learning more accessible to apply on
  low-cost sensor solution
exclude:
- vendor
google_analytics: null
google_search: null
highlighter: rouge
host: 127.0.0.1
kramdown:
  auto_ids: true
  hard_wrap: false
  input: GFM
  syntax_highlighter: rouge
markdown: kramdown
output: web
plugins:
- jekyll-remote-theme
port: 4000
remote_theme: fastai/nbdev-jekyll-theme
repository: austinyhc/sensorai
sidebars:
- home_sidebar
site_title: sensorai
topnav_title: sensorai
use_math: true
